---
  app:
      name: Monitoring Beanstlkd
      host: "<server>:<port>"
      tube: "<tube1>, <tube2>"
      max-buried-job: <threshold-jobs>
      smtp:
        user: "<sender>@<domain>"
        password: "<password>"
        port: "<port>"
        server: "<smtp server>"
        recipient: "<receiver1>, <receiver2> "
        subject: "Service Status"
        ses:
          enabled: true
          aws-key-id: "<your aws key ID>"
          aws-secret-key: "your secret key"
          aws-region: "<your region>"
---